### PR TITLE
footer

### PR DESCRIPTION
**Pull request by matallo**
close https://github.com/CartoDB/website/issues/2672

CR @arianaescobar

### CODE REVIEW

**Comment by arianaescobar** [comment]
[Waiting for tablet layout]

**Comment by arianaescobar** [comment]
- [ ] All the upper part of the design is missing (Subscribe form and social network buttons) 
- [ ] Correct order for the Solutions column:

1. Banking and Finance
2. BI and Analytics
3. Government
4. Real Estate
5. Web Development
6. Journalism
7. Natural Resources
8. Earth Observation
9. Non-Profits
10. Education

**Comment by matallo** [comment]
>  All the upper part of the design is missing (Subscribe form and social network buttons)

this was a decision by @carlostallon and agreed by @saleiva , we were not having the subscribe and social links in the footer but in the home page. I can restore them for sure, anyway.

> Correct order for the Solutions column

:+1:

**Comment by matallo** [comment]
updated

**Comment by arianaescobar** [comment]
Everything looks good, just as on website the margin below everything should be 120px instead of 60px.

**Comment by matallo** [comment]
:rocket:

**Pull request merged**
