### PR TITLE
Fixed 404 on Academy url

### PR DESCRIPTION
**Pull request by beloneys**
CR @arianaescobar

### CODE REVIEW

**Comment by arianaescobar** [comment]
IMO I don't think we should make this change, since it's not the same type of content, let's fix the 404 with the correct link to that legacy lesson and once we have a similar lesson, we'll swap it to learn (my 2 cents, but either way, the change is correct in case you want to go ahead and merge it).

**Comment by beloneys** [comment]
This is the current redirection cc/ @namessanti so please Santi confirm any change.

**Comment by namessanti** [comment]
I'm with Ari on this one..  I added it Learn and we'll put it in the pipeline. 

https://github.com/CartoDB/learn/issues/244

**Comment by beloneys** [comment]
Ok, so please check line 56 of Learn Structure document, as this link was already redirected after having your confirmation in there -I just followed the content directions provided.

So every time I change a 404 I'm checking before this doc, and it happens that when you go to https://carto.com/academy/courses/beginners-course/making-your-first-map/ it already redirects to https://carto.com/learn/guides/styling/animating-maps-with-point-data.

In case you need to change this redirection, it shouldn't be here, it should be in the Learn Structure document please. Let me know once you check the redirections and let me know if you need any change please.

Thanks!

https://docs.google.com/spreadsheets/d/1cuvpqz-ibgQdqQ6X700XL8NVUE2tGdh6GabHN9cSOto/edit#gid=1691627821

**Comment by beloneys** [comment]
hey guys, I'm going to revamp the old content. Santiago let me know in case you wanted it redirected to any new source please

ref: https://mobile.twitter.com/Guillermolo/status/819259991966228480

We need to be fast when doing a bad redirection so we can avoid confused visitors please :)

**Pull request closed without merging**
