### PR TITLE
move academy to _app

### PR DESCRIPTION
**Pull request by matallo**
can be checked in http://academy.cartodb.com/

- moved academy to jekyll3
- replicated new docs design, markup, deploy, ... with the academy

### CODE REVIEW

**Comment by matallo** [comment]
@ohasselblad needs CR

I moved the build and deploy workflow to what we have for the documentation. this varies slightly from the current workflow where we just pushed to gh-pages, and now it is a grunt task.

**Comment by ohasselblad** [comment]
looking now!

**Comment by ohasselblad** [comment]
No issues building academy and running locally :) all LGTM!

**Comment by matallo** [comment]
:raised_hands:

**Comment by matallo** [comment]
btw, I'm changing main branch from gh-pages => master, again

**Comment by ohasselblad** [comment]
ok. does a merge with master trigger a deploy to s3?

**Comment by matallo** [comment]
right now those deploys have are done with a `grunt build` task, until systems setup the hook, but I'm being quite responsive on merging asap a new branch is merged

**Comment by ohasselblad** [comment]
:+1:

**Pull request merged**
