### PR TITLE
Fixes for 2 404s on academy

### PR DESCRIPTION
**Pull request by beloneys**
cr @namessanti

### CODE REVIEW

**Comment by namessanti** [comment]
I think the choropleth link can be changed to our new guide: https://carto.com/academy/courses/beginners-course/your-first-choropleth-map

While it's not completely complimentary probably a good idea to start pointing away from academy (even in Academy)

@arianaescobar are you responsible for merging here also?

**Comment by beloneys** [comment]
Hi @namessanti 

I think you copied the wrong url here (still academy, the same I fixed in the code). Is there a new choropleth guide inside /learn please? Please provide any new url so I can update them on the second sheet of Learn structure, and do the redirections in the first one with your approval :)

https://docs.google.com/spreadsheets/d/1cuvpqz-ibgQdqQ6X700XL8NVUE2tGdh6GabHN9cSOto/edit#gid=1637103861

**Comment by arianaescobar** [comment]
@namessanti I can code review but I believe any of us can merge this kind of changes (but let's always do a code review first!)

**Comment by beloneys** [comment]
Is this the link? I'm updating the urls in the doc from the mail you sent few days ago during my vacation.

Thanks!

https://carto.com/learn/guides/styling/choropleth-map-for-statistical-data

**Comment by namessanti** [comment]
Oops, Update was lost in my emails. That's the one!

**Comment by beloneys** [comment]
Changed, @arianaescobar  for CR

**Comment by arianaescobar** [comment]
retest this please

**Comment by arianaescobar** [comment]
@luisbosque could you shed some light on why this is failing? I took a look at the console output but couldn't understand a thing :(

**Comment by luisbosque** [comment]
I don't have a clear idea about the reason. I'm going to create a issue so we can investigate it

**Comment by arianaescobar** [comment]
Thank you :)

**Comment by arianaescobar** [comment]
retest this please

**Pull request merged**
