### PR TITLE
intermediate design - color lesson part 1 writeup

### PR DESCRIPTION
**Pull request by ztephm**
WIP

### CODE REVIEW

**Comment by ztephm** [comment]
hi @ohasselblad here's WIP w/slider added. Writeup's done but have to redo some images.

hi @carlostallon does the drag/slider style fit with our style?

**Comment by carlostallon** [comment]
Hey @ztephm, can you share an screenshot with me to review the slider?

Thanks :)

**Comment by ztephm** [comment]
here u go @carlostallon 

screen shot 2016-04-19 at 2 54 29 pm

BTW @ohasselblad updated images, only waiting for client's permission to use their map as example.

**Comment by carlostallon** [comment]
Hi again @ztephm, the slider works for me ;)

Thanks!

**Comment by ztephm** [comment]
Great, thanks @carlostallon ! 

@ohasselblad client isn't responding to request to use their map, going to look for another community example.

**Comment by ztephm** [comment]
hi @ohasselblad and @makella found another client example - does this all look ok to publish?

**Comment by makella** [comment]
looks great to me! excellent job.

**Comment by ztephm** [comment]
Thanks @makella ! Got client's OK to use their map as example, so sh/be ok to go @ohasselblad

**Pull request merged**
