### PR TITLE
Added CartoCSS lesson write-up

### PR DESCRIPTION
**Pull request by ztephm**
Fixes https://github.com/CartoDB/academy/issues/157

Hi @ohasselblad please let me know about edits!

cc: @auremoser 

screen shot 2015-06-09 at 1 19 07 pm

screen shot 2015-06-09 at 1 19 32 pm

screen shot 2015-06-09 at 1 35 41 pm

### CODE REVIEW

**Comment by ztephm** [comment]
Updated vid: https://www.dropbox.com/s/o1s4sk3a4pyn3s0/maLite-css-061015.mp4?dl=0

@ohasselblad let me know if it's ok to post to vimeo or needs more edits please

**Comment by ohasselblad** [comment]
LGTM (looks great to me)! Time to upload vid, and update the iframe src!

**Comment by ohasselblad** [comment]
looks super!! :bike:

**Comment by ohasselblad** [comment]
Ref CartoDB/cartodb-management#3860

**Comment by auremoser** [comment]
Great post! @ztephm + @ohasselblad ! Sorry it took me so long to respond :( email fail.

**Comment by ztephm** [comment]
thanks @auremoser ! & no prob, if u happen to have feedback we can still incorporate

**Pull request merged**
