### PR TITLE
added chart + description updates

### PR DESCRIPTION
**Pull request by ztephm**
Got the chart format working @ohasselblad + made some description updates. Look ok?

### CODE REVIEW

**Comment by ohasselblad** [comment]
@ztephm , are there some missing comp ops? Is there an official list for the release of mapnik that we're using? 

I updated it a bit with breakdown by type of comp op (color versus alpha) and then categorized them by font to consolidate the information some. I'm also unsure about some of them (with the question marks).. are they categorized correctly (as color comp ops) and if they're in the spec for our version of mapnik (e.g., `invert-rgb` doesn't throw errors when I use it but I can't seem to produce anything reasonable).

**Comment by ztephm** [comment]
hi @ohasselblad we use a [fork](https://github.com/CartoDB/mapnik/tree/2.3.x.cartodb) of [Mapnik 2.3.]
(https://github.com/CartoDB/mapnik/blob/2.3.x.cartodb/deps/agg/include/agg_pixfmt_rgba.h) These aren't included in that version:

* linear-dodge
* linear-burn
* divide

Rest you had in bold are color comp-ops & are in our version of Mapnik. 

Invert-rgb was working when I tried with a single-color src and texture-filled destination, lmk what you were seeing tho. In some cases color channels and alpha are multiplied together (premultiplied even) so maybe for some of these results were different than results from non-alpha pixel math tests? If needed we can dissect the math [here](https://github.com/CartoDB/mapnik/blob/2.3.x.cartodb/deps/agg/include/agg_pixfmt_rgba.h).

I put clear back in alpha cat b/c it's grouped there in other sources but technically I think it's clearing both alpha & color channels - code's [here](https://github.com/CartoDB/mapnik/blob/2.3.x.cartodb/deps/agg/include/agg_pixfmt_rgba.h#L228) tho, please let me know if I'm wrong! 

Got grunt serve working, I hope different chart fonts are b/c of preview:
screen shot 2015-12-23 at 3 21 49 pm

**Comment by ohasselblad** [comment]
Great :) I'd say put contrast at the bottom of the middle column, and give `clear`, which is an outlier in that it effects alpha and color(?), a sentence of it's own after the chart so the table is balanced on all of the columns. After that, let's merge!

**Comment by ztephm** [comment]
done!

screen shot 2015-12-23 at 3 41 57 pm

**Comment by ohasselblad** [comment]
:bike: :eggplant: :+1: merge at will :) I'll deploy it afterwards (remind me to show you this step later).

**Pull request merged**
