### PR TITLE
added titles for new academy lesson pages

### PR DESCRIPTION
**Pull request by csobier**
Fixes issue #291 .

@ohasselblad , please approve and merge if OK.

### CODE REVIEW

**Comment by ohasselblad** [comment]
:+1: 

While you're at it...

It looks like there are missing titles in this lesson:
* http://academy.cartodb.com/courses/beginners-course/getting-started/

This one isn't formatted correctly (h2 instead of h1?)
* http://academy.cartodb.com/courses/intermediate-design/use-composite-operations/

**Comment by csobier** [comment]
I'm on it! (I'll go through each page and verify all).

**Comment by csobier** [comment]
I think I got them all.  In some cases the title and H1 were different, I used my best judgement for consistency.

**Comment by ohasselblad** [comment]
Looks great, merge at will :+1:

**Comment by ohasselblad** [comment]
actually, merging now :)

**Pull request merged**
