### PR TITLE
[wip] adding community section

### PR DESCRIPTION
**Pull request by ohasselblad**
This PR adds our first lesson(s) to map academy/community.

### CODE REVIEW

**Comment by ohasselblad** [comment]
@piensaenpixel, all is ok to move forward on this. Could you preview the formatting on the lesson information sections? It looks like the margins of the `<p>` could be larger. See [here](https://github.com/CartoDB/academy/pull/201/files#diff-d9f6cda9501e503c4e1fe63235e8cbe1R16) for example:

screen shot 2015-09-08 at 10 35 45

**Comment by auremoser** [comment]
@matallo hey tío, is there a reason this as been closed without merge?

**Comment by matallo** [comment]
sorry it looked like an automatic action by github :disappointed: 

long story: I removed `master` branch and the related PRs got closed I can create a new one for you guys pointing to gh-pages

**Comment by auremoser** [comment]
it's o.k., i just wanted to link to it in an email i'm sending to one of eduardo's contacts and I couldn't find it live. it would be lovely if this could go up today :). Low pressure though, I know you're busy.

**Comment by ohasselblad** [comment]
This wasn't ready to go up yet

On Friday, September 18, 2015, Aurelia Moser <notifications@github.com>
wrote:

> it's o.k., i just wanted to link to it in an email i'm sending to one of
> eduardo's contacts and I couldn't find it live. it would be lovely if this
> could go up today :). Low pressure though, I know you're busy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/academy/pull/201#issuecomment-141472856>.
>


-- 
Andy Eschbacher
Map Scientist
@MrEPhysics

CartoDB--Map Your World's Data
143 Roebling St 2A, Brooklyn, NY, 11211, USA

**Comment by auremoser** [comment]
I'm sorry I thought it was done, do you want to retract and have me delete my tweet? I'm sorry @ohasselblad I saw the issue was closed and it seemed like it was ready.

**Comment by auremoser** [comment]
deleted the tweet, @matallo is retracting.

**Comment by ohasselblad** [comment]
I still need to get the 'ok' from one of the authors, and I'm awaiting some design changes. The 'work in progress' tag means it's not ready to go live.

**Comment by auremoser** [comment]
O.k. I'm sorry. I thought the "wip" was erroneous like the closed issue. My fault, if the author contacts you offended you can blame me and I'll personally write them an apology.

**Pull request closed without merging**
