### PR TITLE
updating to CARTO

### PR DESCRIPTION
**Pull request by mehak-sachdeva**
Changing all 'CartoDB's to 'CARTO'.

cc @ohasselblad

### CODE REVIEW

**Comment by ohasselblad** [comment]
cc @ztephm

**Comment by ohasselblad** [comment]
looks beautiful to me! I checked a couple of the carto(db).js examples to make sure they're working properly, and they are :) Since this is such a big PR @ztephm will be taking a look too. Once she gives a thumbs up merge away!

**Comment by ztephm** [comment]
Great job @mehak-sachdeva ! 

I made a few small edits, mostly changing url's like this:
https://carto.com/docs/cartodb-editor.html
to this:
https://carto.com/docs/carto-editor/
...just something I caught, I know your task was to change CartoDB to CARTO in the paragraph text :)

cc @ohasselblad @csobier 
Some of the urls won't work b/c they are not in our website that I can find any more, like https://carto.com/docs/cartodb-platform/cartodb-js/api-methods/#visaddinfowindowmap-layer-fields--options - but I think we don't have to worry about that in this issue b/c it will be covered in when we open other ones re: updating lesson content.

Otherwise, LGTM!

**Comment by csobier** [comment]
FYI:  I moved all the API infowindow content to the "Specific UI Functions" sections about 6 months ago :-)  (Also, all legacy 'platform" urls are supposed to appear as "engine", so I'm not sure what's going with the website redirects)

https://carto.com/docs/carto-platform/carto-js/ui-functions/#cartodbvisvisaddinfowindowmap-layer-fields--options

**Pull request merged**
